### PR TITLE
Migrate from react scripts to Vite

### PR DESCRIPTION
**Pull request by imjpfeliciano**

### CODE REVIEW

**Comment by tribakzero** [comment]
Thank you for the effort @imjpfeliciano, this totally brings value to the project!
Would you mind adding vitest to the PR? So that the PR Check continues to work as before?

**Comment by imjpfeliciano** [comment]
> Thank you for the effort @imjpfeliciano, this totally brings value to the project! Would you mind adding vitest to the PR? So that the PR Check continues to work as before?

Sure, I'm working on it, will update the PR once I get it done

**Comment by imjpfeliciano** [comment]
Hey @tribakzero could you give me a hint about why the deploy still failing?

I ran out of ideas,

- I have migrated to vite
- Updated vitest to run unit tests
- Upgraded eslint config

**Comment by tribakzero** [comment]
Will take a look at night, thanks again for the effort @imjpfeliciano

**Comment by tribakzero** [comment]
🤔 Managed to get things working here: https://github.com/tribakzero/geaas/pull/41 Let me know your thoughts.

**Pull request closed without merging**
